logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.web.servlet.DispatcherServlet: TRACE
    org.springframework.boot.autoconfigure.web.servlet.error.BasicErrorController: TRACE